# Copyright (c) 2021 Dell Inc, or its subsidiaries.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Get oVirt vms list
  hosts: engine
  gather_facts: false

  roles:
    - { role: ../roles/ovirt.login }

  tasks:
    - name: Get ovirt vm info
      ovirt_vm_info:
        auth: "{{ ovirt_auth }}"
        pattern: "name=*"
        all_content: yes
        fetch_nested: yes
      register: result

    - name: Get ovirt templates info
      local_action:
        module: copy
        content: "{{ result.ovirt_vms |to_nice_json }}"
        dest: "../../ovirt/vms.json"

    - name: Launch logout role
      include_role:
        name: ../roles/ovirt.logout
